// packages/ui/scripts/generate-exports.mjs
import fs from "fs";
import path from "path";

const MODULES_DIR = "./../ui/src/modules";
const INDEX_FILE = "./../ui/src/modules/index.ts";

function generate() {
  // Get all files in modules (excluding test files or index files)
  const files = fs
    .readdirSync(MODULES_DIR)
    .filter(
      (file) =>
        (file.endsWith(".tsx") || file.endsWith(".ts")) &&
        !file.includes(".test.") &&
        file !== "index.ts"
    );

  const exportStatements = files.map((file) => {
    const name = file.replace(/\.(tsx|ts)$/, "");
    return `export * from "./${name}";`;
  });

  // Basic structure for your index.ts
  const content = `// This file is auto-generated by generate-exports.mjs
${exportStatements.join("\n")}
`;

  fs.writeFileSync(INDEX_FILE, content);
  console.log("✅ UI Barrel exports updated successfully.");
}

generate();
