import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  media: defineTable({
    organizationId: v.string(), // CRUCIAL for security (multi-tenancy)
    userId: v.string(), //From Clerk JWT

    // Original Details
    url: v.string(),
    pathname: v.string(),
    name: v.string(),
    mimeType: v.string(),
    size: v.number(),

    // File Type Classification
    type: v.string(), // e.g., 'image', 'video', 'document'

    // If this is null, then this is the original file
    parentId: v.optional(v.id("media")),

    // Varianting (optional) - e.g., thumbnails, optimized versions
    variant: v.optional(v.string()),

    // Categorization (optional)
    category: v.optional(v.string()), // e.g., 'profile_picture', 'document', 'video'
    folderId: v.optional(v.id("folders")), // For organizing files into folders

    // AI & Transformation Metadata
    isModerated: v.boolean(),
    isOptimized: v.boolean(),

    // Tags (for vector search) - Generated by AI
    tags: v.array(v.string()), // e.g., ['coffee', 'mug', 'product photography']

    // Transformation Data (e.g., URL modifiers)
    originalUrl: v.string(),
    // This could store JSON rules for transformations like { w: 800, h: 600, fit: 'cover' }
    transformationRules: v.optional(v.any()),

    // For vector search integration (optional but highly recommended)
    embedding: v.optional(v.array(v.number())),
  })
    // CRITICAL: Always index by organizationId for secure querying
    .index("by_organization", ["organizationId"])
    .index("by_user", ["userId"])
    // Recommended: Index by organization and file type for fast filtering in the dashboard
    .index("by_org_type", ["organizationId", "mimeType"])
    // Recommended: Index for fast search/filtering in the embeddable widget
    .searchIndex("search_tags", {
      searchField: "tags",
      filterFields: ["organizationId"], // Only search within the tenant
    })
    .index("by_parent", ["parentId"])
    .index("by_category", ["category"])
    .index("by_folder", ["folderId"])
    .index("by_organization_category", [
      "organizationId",
      "category",
    ]),

  folders: defineTable({
    organizationId: v.string(), // CRUCIAL for security (multi-tenancy)
    createdByUserId: v.string(), //From Clerk JWT
    isPublic: v.boolean(),
    name: v.string(),
    parentFolderId: v.optional(v.id("folders")),
  }).index("by_organization", ["organizationId"]),
});
